### ISSUE TITLE
Pokebox to add tagging

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#543]
Insert a section for tag management in-between (result count) and (inputs).
This section should allow adding/modifying/deleting tags.

In Poke-in-box editing popup, add a row for selecting tags, utilizing `<FilterExpandedInputs/>`.

In Pokebox view, show tags in the info section, with small texts.

Colors should be predefined for easier theming.

## TODO

- [x] Page for editing tags
- [x] Revamp Pokebox top action bar
- [x] Poke-in-box editing layout to allow adding tags
- [x] Pokebox to show tags under the name (smaller text size if tags available)
- [x] Allow filtering Poke-in-box using tags
- [x] Pokebox add action to open a new tab for tag management
- [x] Premium only

## Sample images from Pokemon Go

![Image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/66c875e7-5b6c-47e6-938f-5d0749e871e6)

![Image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/a6aae8d5-0a7c-403b-8f25-521b51df048f)

![Image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/4361badc-50eb-4848-a013-97f6f9d88c6a)
